### PR TITLE
Add Peddie Institute Test Root to Dodo

### PR DESCRIPTION
**Pull request by PDEDU**
CN: Peddie Institute Root Certificate Authority DEV

### CODE REVIEW

**Comment by robstradling** [comment]
Hi.  I'll confirm here when this has been added to Dodo's list of accepted roots.

**Comment by PDEDU** [comment]
OK. Thank you :)

**Comment by robstradling** [comment]
This root is now accepted by Dodo.

**Comment by PDEDU** [comment]
THANK YOU!!! :-)

**Pull request merged**
